### User Signup API


# POST https://clf.ewigsol.com/wp-json/wc/v3/customers HTTP/1.1
# Content-Type: "application/json",
# # Content-Length: "81",
# consumer_secret: "cs_d7dd31edbb0125fc1c9e54e96a6731b5d96f7788",
# consumer_key: "ck_54241d87566696586ecd54b1ed72a7c69eb07f86"
# # Authorization: : "Basic Y2tfNTQyNDFkODc1NjY2OTY1ODZlY2Q1NGIxZWQ3MmE3YzY5ZWIwN2Y4Njpjc19kN2RkMzFlZGJiMDEyNWZjMWM5ZTU0ZTk2YTY3MzFiNWQ5NmY3Nzg4"


# {
#     "username" : "zainsyed",
#     "password" : "123456789",
#     "email" : "info@ewigsol.com"
# }

POST https://clf.ewigsol.com/wp-json/wc/v3/customers HTTP/1.1

consumer_secret: "cs_d7dd31edbb0125fc1c9e54e96a6731b5d96f7788",
consumer_key: "ck_54241d87566696586ecd54b1ed72a7c69eb07f86"
Content-Type: "application/json",


content
{
  "email": "john.doe@example.com",
  "first_name": "John",
  "last_name": "Doe",
  "username": "john.doe",
  "billing": {
    "first_name": "John",
    "last_name": "Doe",
    "company": "",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US",
    "email": "john.doe@example.com",
    "phone": "(555) 555-5555"
  },
  "shipping": {
    "first_name": "John",
    "last_name": "Doe",
    "company": "",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US"
  }
}